/**
 * Regenerates src/components/SkillIcon.tsx from the simple-icons package.
 *
 * simple-icons is NOT a project dependency — the generated paths are committed,
 * so the build doesn't need it. To add or change an icon:
 *
 *   npm install --no-save simple-icons
 *   node scripts/gen-icons.mjs
 *
 * Add the new entry to `want` below (key = the `icon` value used in
 * src/content/portfolio.ts, value = the exact Simple Icons title), or to
 * `custom` if Simple Icons doesn't carry the mark.
 */
import * as si from "simple-icons";
import { writeFileSync } from "node:fs";

const want = {
  react: "React", vue: "Vue.js", typescript: "TypeScript", javascript: "JavaScript",
  redux: "Redux", pinia: "Pinia", vite: "Vite", jest: "Jest",
  dotnet: ".NET", python: "Python", fastapi: "FastAPI", flask: "Flask",
  node: "Node.js", postgresql: "PostgreSQL", mongodb: "MongoDB", redis: "Redis",
  graphql: "GraphQL", docker: "Docker", terraform: "Terraform", git: "Git",
  githubactions: "GitHub Actions", datadog: "Datadog", mlflow: "MLflow",
  langgraph: "LangGraph", java: "OpenJDK", jenkins: "Jenkins",
  octopusdeploy: "Octopus Deploy", postman: "Postman", jira: "Jira",
};

const icons = {};
for (const [key, title] of Object.entries(want)) {
  const found = Object.values(si).find((i) => i && i.title === title);
  if (!found) throw new Error("missing " + title);
  icons[key] = found.path;
}

// Generic glyphs for marks simple-icons does not carry (trademark removals)
// or that are concepts rather than products.
const custom = {
  // cylinder — generic database
  database: "M12 2C7.58 2 4 3.34 4 5v14c0 1.66 3.58 3 8 3s8-1.34 8-3V5c0-1.66-3.58-3-8-3zm0 2c3.87 0 6 1.07 6 1s-2.13 1-6 1-6-1.07-6-1 2.13-1 6-1zm6 15c0 .07-2.13 1-6 1s-6-.93-6-1v-2.23c1.61.72 4.14 1.23 6 1.23s4.39-.51 6-1.23V19zm0-4.5c0 .07-2.13 1-6 1s-6-.93-6-1v-2.23c1.61.72 4.14 1.23 6 1.23s4.39-.51 6-1.23v2.23zm0-4.5c0 .07-2.13 1-6 1s-6-.93-6-1V7.77C7.61 8.49 10.14 9 12 9s4.39-.51 6-1.23V10z",
  // cloud — generic cloud provider
  aws: "M19.35 10.04A7.49 7.49 0 0 0 12 4C9.11 4 6.6 5.64 5.35 8.04A5.994 5.994 0 0 0 0 14c0 3.31 2.69 6 6 6h13c2.76 0 5-2.24 5-5 0-2.64-2.05-4.78-4.65-4.96z",
  // layered documents — retrieval-augmented generation
  rag: "M14 2H6a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V8l-6-6H6zm-1 7V3.5L18.5 9H13zM4 20V6H2v14a2 2 0 0 0 2 2h14v-2H4z",
  // connected nodes — vector store / embeddings
  vectorstore: "M12 2a2.5 2.5 0 0 0-1 4.79v2.42a2.5 2.5 0 0 0-1.2.7L7.3 8.47a2.5 2.5 0 1 0-1 1.73l2.5 1.44a2.5 2.5 0 0 0 0 .72l-2.5 1.44a2.5 2.5 0 1 0 1 1.73l2.5-1.44c.34.32.75.56 1.2.7v2.42a2.5 2.5 0 1 0 2 0v-2.42c.45-.14.86-.38 1.2-.7l2.5 1.44a2.5 2.5 0 1 0 1-1.73l-2.5-1.44a2.5 2.5 0 0 0 0-.72l2.5-1.44a2.5 2.5 0 1 0-1-1.73l-2.5 1.44a2.5 2.5 0 0 0-1.2-.7V6.79A2.5 2.5 0 0 0 12 2z",
};

const all = { ...icons, ...custom };
const esc = (s) => s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');

const entries = Object.entries(all)
  .map(([k, p]) => `  ${k}:\n    "${esc(p)}",`)
  .join("\n");

const file = `/**
 * Inline SVG skill glyphs.
 *
 * Product marks come from Simple Icons (CC0). A few entries are generic
 * hand-drawn glyphs: \`database\`, \`aws\` (marks Simple Icons no longer carries
 * for trademark reasons), and \`rag\` / \`vectorstore\` (concepts, not products).
 *
 * Generated by scripts/gen-icons.mjs — re-run that rather than editing by hand.
 */
const PATHS: Record<string, string> = {
${entries}
};

interface SkillIconProps {
  icon: string;
  className?: string;
}

export function SkillIcon({ icon, className = "" }: SkillIconProps) {
  const path = PATHS[icon];
  if (!path) return null;

  return (
    <svg
      viewBox="0 0 24 24"
      fill="currentColor"
      aria-hidden="true"
      focusable="false"
      className={className}
    >
      <path d={path} />
    </svg>
  );
}
`;

writeFileSync("src/components/SkillIcon.tsx", file);
console.log("wrote " + Object.keys(all).length + " icons");
